### ISSUE TITLE
Convert week date into time

### ISSUE THREAD

**Issue by stoewer** [stoewer/go-week#3]
Add a method `Time()` that turns a week date into [`time.Time`](https://golang.org/pkg/time/#Time)

**Comment by krnkl** [comment]
What time it should return? First second of the Monday of the week?

**Comment by stoewer** [comment]
I'd suggest to return Monday 00:00:00. If the calendar week is 2018-W16 where Monday is 2018-04-16 `Time()` should return 2018-04-16T00:00:00.000Z.

**Comment by krnkl** [comment]
What about providing week day as a parameter - it will be even more flexible.
`func (w *Week) Time(weekday ...time.Weekday) time.Time`
or without variadic parameter:
`func (w *Week) Time(weekday time.Weekday) time.Time` 
then day will be always excplicitly set.

**Comment by stoewer** [comment]
Good idea! I like the second one without the variadic parameter better.
